### ISSUE TITLE
Proxy and cookies?

### ISSUE THREAD

**Issue by gcscaglia** [mauzel/mproxy-gbf#5]
As of https://bugs.chromium.org/p/chromium/issues/detail?id=369911, Chrome does not send any cookies through proxies of any sort. When using mproxy-gbf, this creates problems with language settings and likely with login info too.

While I realize mproxy-gbf has no ways to fix this (short of handling cookies itself - very hacky) I'm wondering if there isn't a workaround; For example, a specially crafted PAC file to send only cacheable assets requests through the proxy, and if you wouldn't have pointers on how to achieve that?

**Comment by mauzel** [comment]
Sorry for the late reply.

> When using mproxy-gbf, this creates problems with language settings and likely with login info too.

Interesting, but I haven't encountered any issues. If you have experienced issues, how does it manifest?

I use JP language, and also I have not experienced any issues with authentication. If it does manifest for you, I would like to know how it manifests to see if I can reproduce the issue.

> For example, a specially crafted PAC file to send only cacheable assets requests through the proxy, and if you wouldn't have pointers on how to achieve that

If this is indeed an issue, then yes, you can make a PAC file which achieves this (I think). Basically, write a regular expression that only matches images/audio files.

**Comment by mauzel** [comment]
To add, I believe that login cookies are handled via an entirely different domain (for example, *.mbga.jp and not granbluefantasy.jp), which may be why I haven't seen this issue.

**Comment by mauzel** [comment]
Closing since this issue is now stale.
