### ISSUE TITLE
Don't cache the captcha image

### ISSUE THREAD

**Issue by mauzel** [mauzel/mproxy-gbf#6]
If you get captcha'd, the captcha image gets cached so you have to turn off the proxy or delete the cached captcha image whenever you get captcha'd.

This is bad because it's annoying and people probably won't understand why they keep getting the same captcha image and failing it.

**Comment by AkagiShiroe** [comment]
still not fixed? btw captcha only show in casino right?

**Comment by mauzel** [comment]
@AkagiShiroe Sorry, I got busy with work and never got around to this. I'm going to try to fix it now.

I've never seen a captcha in casino, so if there is one, I would be interested in seeing it.

The captcha I am referring to is one they show you on the summon select page. If you play the game a lot, you will sometimes get a simple captcha pop up when you select a summon.

**Comment by mauzel** [comment]
This issue is in theory fixed by pull request with commit fcfe86f326e03a88fa3c6eab3be2edda5b63b008
