### ISSUE TITLE
Additional Log Information

### ISSUE THREAD

**Issue by AkagiShiroe** [mauzel/mproxy-gbf#7]
could you insert information like "succesfull fetch xxx file" and "skip file" for verified files in console?

**Comment by mauzel** [comment]
Hi, could you elaborate a bit more on what you mean? I don't mind adding additional logging, but I am unsure what exactly you want to see information for and in what situation.

**Comment by AkagiShiroe** [comment]
@mauzel  actually sometimes my network are fail to load file properly (freezing), so the soft just basically save corrupted cache (which is i had hard time to find which one), but thanks for a good code, this thing help me and my friend. and also.. your code are 2.7 nee~

**Comment by mauzel** [comment]
> so the soft just basically save corrupted cache (which is i had hard time to find which one)

Maybe you already figured this out, but the `cache/.cache_list` file can help a little bit.

So for example, in Chrome you identify the corrupted file's URL. You can do this by right clicking on the image in Chrome and click "Inspect" and find the URL. Let's say the URL for the corrupted file is

```
http://game-a1.granbluefantasy.jp/assets/img/sp/banner/gacha/banner_1203_7l82li7c.png
```

Then open the `cache/.cache_list` file and search for that URL, and you will see something like:

```
...
"d60b6cfb1cbebca397ba050abd9929a7a492e863","http://game-a1.granbluefantasy.jp/assets/img/sp/banner/gacha/banner_1203_7l82li7c.png","35651"
...
```

Then you can delete the corrupted file `d60b6cfb1cbebca397ba050abd9929a7a492e863` from the `cache/` directory and it will get cached again later.

But ideally, mproxy-gbf would automatically update the cache periodically to ensure there are no corruption and no old cache files... but that's future work.

**Comment by AkagiShiroe** [comment]
yeah need hell-a-improvement but still good code to solve my caching issue and speed loading
